Task 5 modal
js-tasks-ru/htmlcss-20240216_alexandralexv pull request #10
Opened 2024-03-10 19:43 UTC by Alexandralexv

2024-03-10 19:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-10 19:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-12 14:02 UTC, GSemikozov requested changes

2024-03-12 14:02 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
принципиально fixed

2024-03-12 14:02 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
и еще здесь же добавляем фон через rgba

2024-03-12 14:02 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__opacity {
чтобы не создавать этот лишний элемент (удалим)

2024-03-12 14:02 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +чтобы прозрачность не передовалась наследникам.
см коммент выше

2024-03-12 14:02 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.container {
зачем?)

2024-03-12 14:02 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.container__main {
.modal__window

2024-03-12 14:02 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    top: 0;
центрируем по середине как и на уровне где рассматривали тему position

2024-03-12 14:02 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button {
это не часть блока и кнопка у нас уже есть сверстанная, так что удаляем

2024-03-12 14:02 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.container__flex {
отсюда и ниже - мы верстаем не контейнер и его элементы, а модалку и ее элементы, так что просьба поправить все классы по БЭМ :)

2024-03-12 14:02 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    margin: -18px -28px 0 0;
проще через абсолют

2024-03-12 14:02 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    margin: 0 40px 33px 0px;
проще на уровне родителя задать общие паддинги

2024-03-12 15:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-13 12:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-13 12:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-14 13:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-14 14:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-14 14:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-14 14:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-14 15:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-14 15:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-14 15:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-14 15:44 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +чтобы прозрачность не передовалась наследникам.
Протест.

2024-03-14 15:44 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
Протест.

2024-03-14 15:47 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +.modal__opacity {
см. выше

2024-03-14 15:47 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +чтобы прозрачность не передовалась наследникам.
см. выше

2024-03-14 15:52 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +.container {
Не знаю)
Исправил.

2024-03-14 15:54 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +.container__main {
Согласен. Исправил.

2024-03-14 15:55 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
В фигме прозрачность мы делаем через opacity: 0.5; Я обыскал весь интернет, везде сказали, что невозможно отменить эту штуку у наследника и поэтому надо использовать rgba, Но я не сдался и нашёл, как по мне, крутой способ, чтобы у наследника не было opacity: 0.5; Не понимаю, зачем перестраивать под rgba, если мой способ работает, так как в фигме прописано)

2024-03-14 15:59 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +    margin: 0 40px 33px 0px;
Исправил.

2024-03-14 15:59 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +    margin: 0 40px 33px 0px;
Они там были, но из-за абсолюта, непонятно зачем написанного, не работали.

2024-03-14 16:03 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +    margin: -18px -28px 0 0;
Согласен. Оказалось очень просто, не знаю, почему я так люблю через минусы высчитывать :)

2024-03-14 16:05 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +.container__flex {
Сделал.
В один момент переклинило меня. Увидел как вы классно через контейнер сделали одну штуку и везде стал тоже пихать контейнер.
Ошибка? - Фатальная Ошибка...

2024-03-14 16:07 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +.button {
Не очень понял, что надо сделать? Нам же нужна кнопка, как мы её удалим? Или имелось ввиду поменять название на modal__button, если так, то я поменял

2024-03-14 16:10 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +.button {
+ Я же не могу переиспользовать кнопку. т.к. они в разных заданиях. Но я взял всё из класса той кнопки, которую мы уже создавали и поместил сюда. Не очень понял, что Вы имели ввиду.

2024-03-14 16:14 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +    top: 0;
Где? Там где мы абсолют на fixed поменяли. но мы там не центрировали. Почему мой способ центрации(есть же такое слово?) не подходит?
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
По факту же получается центр?

2024-03-14 16:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-14 16:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-15 14:56 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
через отдельный элемент? усложняя верстку? зачем? если можно сделать намного проще)

2024-03-15 15:02 UTC, GSemikozov requested changes

2024-03-15 15:02 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    top: 0;
top: 0;
left: 0;
right: 0;
bottom: 0;
==> это не центрирование, это растягивание блока по своему родителю. Чтобы центрировать элемент, не привязываясь к размерам элемента, надо использовать смещение на половину родителя вниз и вправо, а потом на половину ширины элемента сместить назад - влево и наверх.

2024-03-15 15:02 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    top: 0;
с top: 0;left: 0;right: 0;bottom: 0; раблотает потому, что размеры четко определены

2024-03-15 15:03 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button {
а мы кнопки до сих пор не приняли?

2024-03-15 15:03 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button {
вот же они, в мастере https://github.com/js-tasks-ru/htmlcss-20240216_alexandralexv/blob/master/03-lection1/01-button/button.css

2024-03-15 15:03 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button {
они подключаются в main.css, вот и все

2024-03-15 15:05 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button {
не надо дублировать код, это против принципа переиспользования (представим, что такие кнопки используются в 20 компонентах и мы во всех 20 компонентах вместо того чтобы использовать уже имеющиеся стили, будем их копипастить. А потом придет дизайнер и попросит поменять цвет бордера - и пойдем мы гулять по проекту и менять везде все ручками =))

2024-03-17 18:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-17 18:38 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
Исправил. И правда, просто :)

2024-03-17 18:39 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
Но я не очень понял, как подбирать цвета, если в фигме они указаны просто в bacground, без rgba. Я в интернете нашёл, но могу же и не найти, как тогда поступать с цветом?

2024-03-17 18:52 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +    top: 0;
Исправил

2024-03-17 18:53 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +.button {
Давайте тут( в задачке) оставим этот код, А когда я буду переносить на главную страницу, там будет уже в разных папках(в папке компонентов) просто сейчас, её банально там нет, т.к. это делалось ещё когда Вы не приняли кнопки.

2024-03-17 18:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-18 15:39 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
любой онлайн конвертер :) https://rgbacolorpicker.com/hex-to-rgba

2024-03-18 15:39 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button {
неа, так низзя :)

2024-03-18 17:35 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
Спасибо! Сохраню!

2024-03-18 18:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-18 18:12 UTC, Alexandralexv commented on 05-lection3/02-modal/modal.css
> +.button {
Спасибо, что на семинаре объяснили. Теперь всё понял. Переделал!

2024-03-18 18:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-20 15:33 UTC, GSemikozov approved these changes
поставлю аппрув, но - Кнопки у нас все равно уже есть, нет необходимости дублировать)

2024-03-20 15:33 UTC, merged