Component page
js-tasks-ru/htmlcss-20240216_alexandralexv pull request #11
Opened 2024-03-19 15:54 UTC by Alexandralexv

2024-03-19 15:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-20 15:38 UTC, GSemikozov requested changes

2024-03-20 15:38 UTC, GSemikozov commented on components/header/header.css
> +    height: 82px;
это лишние стили, а вот что реально меняется - это фон

2024-03-20 15:38 UTC, GSemikozov commented on components/main/main.css
> +    padding: 36px 165px;
паддинги по крафм не нужны, мы используем контейнер)

2024-03-20 15:38 UTC, GSemikozov commented on components/menu/menu.css
> +    height: 22px;
лишнее ограничение

2024-03-21 14:23 UTC, Alexandralexv commented on components/header/header.css
> +    height: 82px;
Исправил.
Просто на фигме так и Вы говорили, что тут размер задаём, т.к. она пока без внутренностей.

2024-03-21 14:23 UTC, Alexandralexv commented on components/header/header.css
> +    height: 82px;
Фон поменял.

2024-03-21 14:37 UTC, Alexandralexv commented on components/main/main.css
> +    padding: 36px 165px;
Исправил

2024-03-21 14:38 UTC, Alexandralexv commented on components/menu/menu.css
> +    height: 22px;
Оно нужно, чтобы был пробел
![image](https://github.com/js-tasks-ru/htmlcss-20240216_alexandralexv/assets/122827524/719aaba1-38ce-40db-b28e-e29c1276dc24)

2024-03-21 14:39 UTC, Alexandralexv commented on components/menu/menu.css
> +    height: 22px;
Если убрать, то будет не по фигме и не красиво.
![image](https://github.com/js-tasks-ru/htmlcss-20240216_alexandralexv/assets/122827524/454001e1-a92e-4979-86f9-6f032a11913f)

2024-03-22 17:05 UTC, GSemikozov commented on components/menu/menu.css
> +    height: 22px;
ну, использовать пустой элемент пункта меню чтобы задавать отступ между двумя элементами - так себе идея) проще добавить на последний элемент модификатор и оформить отступ

2024-03-22 17:06 UTC, GSemikozov requested changes
конфликт

2024-03-23 17:24 UTC, Alexandralexv commented on components/menu/menu.css
> +    height: 22px;
Согласен. Спасибо! исправил.

2024-03-24 15:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-24 15:04 UTC, GSemikozov requested changes

2024-03-24 15:04 UTC, GSemikozov commented on components/container/container.css
> +    margin: 0 165px;
нет, было правильно)

2024-03-24 15:42 UTC, Alexandralexv commented on components/container/container.css
> +    margin: 0 165px;
Я знаю, но тогда вот так получается
![image](https://github.com/js-tasks-ru/htmlcss-20240216_alexandralexv/assets/122827524/f7467682-b654-4773-8ec6-edd6d1562285)
А если с 165px, то нормально
![Uploading image.png…]()

2024-03-24 15:42 UTC, Alexandralexv commented on components/container/container.css
> +    margin: 0 165px;
![image](https://github.com/js-tasks-ru/htmlcss-20240216_alexandralexv/assets/122827524/a55cc1d6-0a47-4502-9c4f-bb0de1cd7515)

2024-03-24 19:09 UTC, Alexandralexv commented on components/container/container.css
> +    margin: 0 165px;
Исправил

2024-04-01 17:55 UTC, GSemikozov requested changes
конфликт

2024-04-02 14:15 UTC, Alexandralexv commented
Устранил конфликт

2024-04-03 19:55 UTC, GSemikozov approved these changes

2024-04-03 19:55 UTC, merged