task 7 checkbox
js-tasks-ru/htmlcss-20240216_alexandralexv pull request #18
Opened 2024-03-27 16:09 UTC by Alexandralexv

2024-03-27 16:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-01 17:58 UTC, GSemikozov requested changes

2024-04-01 17:58 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.container-flex {
этов раппер который не является частью блока, так что удаляем)

2024-04-01 17:58 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__label_disabled {
на этот случай тогда лучше общий модификатор блока .checkbox_disabled

2024-04-02 14:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-04 07:06 UTC, Alexandralexv commented on 07-lection5/01-checkbox/checkbox.css
> +.container-flex {
Исправил.
Но они тогда будут в строчку. А в макете были в столбик.

2024-04-04 07:07 UTC, Alexandralexv commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__label_disabled {
Исправил

2024-04-04 07:08 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-08 14:21 UTC, GSemikozov approved these changes

2024-04-08 14:22 UTC, merged