Task 7 input
js-tasks-ru/htmlcss-20240216_alexandralexv pull request #22
Opened 2024-04-11 19:01 UTC by Alexandralexv

2024-04-11 19:01 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-14 11:55 UTC, GSemikozov requested changes

2024-04-14 11:55 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <input type="text" class="input__input input__input_focus" placeholder="Placeholder">
input__input_focus - лишний модификатор, используем input__input:focus

2024-04-14 11:55 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    right: 16px;
по умолчанию - `display: none`

2024-04-14 11:55 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__input_focus:focus {
фокус у фокуса) см коммент выше

2024-04-14 11:55 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__input_error {
.input_error .input__input {}

2024-04-16 17:12 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-16 17:16 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-16 17:30 UTC, Alexandralexv commented on 07-lection5/04-input/input.css
> +    right: 16px;
Да. но у нас состояния статические, а не изменяющиеся. Следовательно у обычного input'а иконки просто нет, а у второго и третьего input'а они заранее определены и они не скрыты. Потом с помощью джава скрипта мы их подключим и вместо обычного input'а будут появляться эти при введение правильного ввода и неправильного.

2024-04-16 17:33 UTC, Alexandralexv commented on 07-lection5/04-input/index.html
> +            <input type="text" class="input__input input__input_focus" placeholder="Placeholder">
.input__input_focus:focus {
    border: 1px solid #4263EB;
}

.input__input_error {
    border-color: #F03D3E;
}

Отвечают за цвет обводки при наведение/(или статично).

2024-04-16 17:35 UTC, Alexandralexv commented on 07-lection5/04-input/index.html
> +            <input type="text" class="input__input input__input_focus" placeholder="Placeholder">
А с помощью outline: none; я убираю базовую обводку при наведение на input. Получается при наведение на первый input у нас срабатывает обводка, а у второго она выключена и не срабатывает, в случае, если сделать input__input:focus, то она будет у всех срабатывать, что не правильно.

2024-04-16 17:35 UTC, Alexandralexv commented on 07-lection5/04-input/input.css
> +.input__input_error {
см выше

2024-04-16 17:35 UTC, Alexandralexv commented on 07-lection5/04-input/input.css
> +.input__input_focus:focus {
см выше

2024-04-16 21:01 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <input type="text" class="input__input input__input_focus" placeholder="Placeholder">
еще раз: a зачем нам .input__input_focus? состояние фокус нужно описывать через встроенные псевдоклассы, в данном случае речь про :focus

2024-04-16 21:02 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    right: 16px;
нет, состояние у нас будет динамически меняться, когда через js при валидации будет добавлять нужный класс, и будет меняться вся отрисовка

2024-04-16 21:23 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__input_focus:focus {
.input__input_focus:focus --> .input__input:focus

2024-04-16 21:24 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__input_error {
см выше

2024-04-16 21:24 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    right: 16px;
так что иконки у нас должны быть всегда в разметке

2024-04-17 13:40 UTC, Alexandralexv commented on 07-lection5/04-input/index.html
> +            <input type="text" class="input__input input__input_focus" placeholder="Placeholder">
У нас же фокус тогда будет у всех. А нам нужен фокус только у первого!

2024-04-17 13:41 UTC, Alexandralexv commented on 07-lection5/04-input/input.css
> +.input__input_focus:focus {
Фокус тогда у всех будет!!!!

2024-04-17 13:41 UTC, Alexandralexv commented on 07-lection5/04-input/input.css
> +.input__input_error {
см выше

2024-04-17 13:42 UTC, Alexandralexv commented on 07-lection5/04-input/input.css
> +    right: 16px;
Тогда нужно будет добавлять доп модификатор, который будет скрывать эту иконку, да?

2024-04-17 13:57 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-17 14:03 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-17 14:06 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-17 14:08 UTC, Alexandralexv commented on 07-lection5/04-input/index.html
> +            <input type="text" class="input__input input__input_focus" placeholder="Placeholder">
Зачем нам синий фокус в SUCCESS и ERROR?

2024-04-17 14:23 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-18 12:48 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <input type="text" class="input__input input__input_focus" placeholder="Placeholder">
какое сообщение?) success применится и будет видимым в том случае если форма не отправится и будут какие-то ошибки в других полях

2024-04-18 12:49 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__input_error {
да, нет смысла плодить и поддерживать однотипные модификаторы которые привязаны к одному стейту

2024-04-18 12:50 UTC, GSemikozov approved these changes

2024-04-18 12:50 UTC, merged