Task 3 button
js-tasks-ru/htmlcss-20240216_alexandralexv pull request #3
Opened 2024-02-27 15:06 UTC by Alexandralexv

2024-02-27 15:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-02-27 17:20 UTC, Alexandralexv commented
Когда делал кнопки, немного позабыл про opacity для кнопок с disabled, поэтому вместо него поставил свойство filter. 
.button:disabled {
    filter: blur(0.7px);
}
Разные свойства...Но, можно уже так и оставить?

2024-02-29 16:03 UTC, Alexandralexv commented
Решил доделать код, т.к. Вы его ещё не проверили. Поменял на нужную переменную.

Цвета пока намеренно не делаю через переменные, т.к. это отдельные задачи. В Home-page уже начал использовать первые цвета, заданные переменными, т.к. это основной проект

2024-03-03 13:30 UTC, GSemikozov requested changes

2024-03-03 13:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +h1 {
это что-то лишнее, в файле стилей конкретного компонента могут стили только дл] этого компонента

2024-03-03 13:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    position: relative;
в принципе лишнее

2024-03-03 13:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background-color: white;
лишнее

2024-03-03 13:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
лишнее ограничение ширины

2024-03-03 13:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
не хватает line-height + font-family

2024-03-03 13:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border-radius: 20px;
по макету 8

2024-03-03 13:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary {
это модификатор, следовательно `button_primary`

2024-03-03 13:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition-duration: .5s;
transition-duration пока везде удалим

2024-03-03 13:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary_disabled:disabled {
у нас будет общий .button:disabled, не нужно лишних модификаторов.
а в стилях - всего лишь это:
```
opacity: 0.5;
pointer-events: none;
```

2024-03-03 13:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    color: black;
а зачем?

2024-03-03 13:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
уже указано на уровне блока

2024-03-03 14:04 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +h1 {
Согласен. Исправил.

2024-03-03 14:05 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +    position: relative;
Исправлено.

2024-03-03 14:12 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +    background-color: white;
Исправлено.

2024-03-03 14:14 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +    width: 189px;
Исправлено.
Но мне, кажется, что так красивее :)

2024-03-03 14:14 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
Добавил.

2024-03-03 14:14 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +    border-radius: 20px;
Исправлено.
Я думал, что не обязательно всё по шаблону делать.

2024-03-03 14:16 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +.button__primary {
Исправлено.
Это был элемент, но теперь будет модификатор :)
Я уже понял в чём ошибка была. Я думал, что можно в одном классе писать сразу и блок и элемент.

2024-03-03 14:16 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +    transition-duration: .5s;
Удалил

2024-03-03 14:17 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +.button__primary_disabled:disabled {
Исправлено.

2024-03-03 14:19 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +    color: black;
Надо! Не исправлено.
Фон белый и шрифт белый(задан в блоке), если убрать, то шрифт с фоном сольётся. Мне показалось, что легче изначально задать белый шрифт(т.к. кнопок с белым шрифтом по макету больше), а чёрный шрифт прописать уже в отдельных кнопках)

2024-03-03 14:20 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
Не указано. Но я указал, а из модификаторов убрал.

2024-03-04 13:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
а если добавить вот такую строку текста внутрь?) `kfvbkdfnvjdfkvndflvdfvndfndfvdfvd`

2024-03-04 13:55 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    color: black;
дело в том что там цвет текста не черны а `#495057` )

2024-03-04 13:57 UTC, GSemikozov requested changes

2024-03-04 13:57 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    height: 48px;
не хватает паддингов (сразу подскажу - `15 15 14`)

2024-03-04 13:57 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary_disabled {
про disabled писал, что лишнее надо удалить

2024-03-04 13:57 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__secodary_disabled {
удалить

2024-03-04 13:57 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background-color: white;
transparent

2024-03-04 13:57 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background-color: grey;
точно меняется фон? если да, то берем из дизана

2024-03-04 13:57 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__alternate_disabled {
удалить

2024-03-04 13:57 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +        <button class="button button__primary_disabled" disabled="disabled">Primary disabled</button>
disabled="disabled" => disabled

2024-03-04 16:47 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +    width: 189px;
Понял

2024-03-04 16:51 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +    color: black;
...

2024-03-04 16:51 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +    color: black;
у меня слов нет...

2024-03-04 16:53 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +    height: 48px;
Исправлено.

2024-03-04 16:55 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +.button__alternate_disabled {
Понял. Исправил

2024-03-04 16:56 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +.button__secodary_disabled {
Удалил.

2024-03-04 16:56 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +.button__primary_disabled {
Удалил.

2024-03-04 16:57 UTC, Alexandralexv commented on 03-lection1/01-button/index.html
> +        <button class="button button__primary_disabled" disabled="disabled">Primary disabled</button>
Если я правильно понимаю о чём вы, то я понял)

2024-03-04 16:58 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +    background-color: grey;
Не меняется, но там состояния active нет(в фигме). Цвет убрал
![image](https://github.com/js-tasks-ru/htmlcss-20240216_alexandralexv/assets/122827524/e208397e-5a95-4e90-804f-1c07a530fc6d)

2024-03-04 17:01 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +    background-color: white;
Не знал о таком. Исправил.

2024-03-04 21:52 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background-color: grey;
active = hover

2024-03-04 21:53 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +        <button class="button button__primary_disabled" disabled="disabled">Primary disabled</button>
`<button class="button button_primary" disabled>` :)

2024-03-05 07:21 UTC, Alexandralexv commented on 03-lection1/01-button/index.html
> +        <button class="button button__primary_disabled" disabled="disabled">Primary disabled</button>
Вот теперь понял)

2024-03-05 07:23 UTC, Alexandralexv commented on 03-lection1/01-button/button.css
> +    background-color: grey;
но это же разные состояния?
hover - наводит курсор
active - зажимает курсор

2024-03-05 21:26 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background-color: grey;
да, но стили - одинаковые

2024-03-05 21:27 UTC, GSemikozov approved these changes

2024-03-05 21:27 UTC, merged