Task 3 accordion
js-tasks-ru/htmlcss-20240216_alexandralexv pull request #4
Opened 2024-02-27 16:40 UTC by Alexandralexv

2024-02-27 16:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-03 13:35 UTC, GSemikozov requested changes

2024-03-03 13:35 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  border: 2px solid black;
точно 2?

2024-03-03 13:35 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  border-radius: 10px;
точно 8?)

2024-03-03 13:35 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  padding: 0.5em 0.5em 0.5em;
а если в пикселях - то чему равны эти паддинги?)

2024-03-03 13:35 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion accordion__item ">
сын одновременно свой папа? (блок одновременно элемент?)

2024-03-03 13:35 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion accordion__item ">
общая структура должна быть такой:
```
div.accordion
    details.accordion__item
        summary.accordion__title
        div.accordion__content
```

2024-03-03 13:35 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion {
см коммент ниже (верстаем 1 блок с 3 секциями а не 3 отдельных блока + нельзя смешить классы блоков с классами элементов, а элементы - путать с модификаторами). Важно исправить везде

2024-03-03 13:35 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  margin-bottom: 8px;
не хватает стилей для описания текста. И - паддинги нужно задавать именно здесь

2024-03-03 13:35 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.summary {
блок? или все-таки элемент аккордиона .accordion__summary?

2024-03-03 14:23 UTC, Alexandralexv commented on 03-lection1/02-accordion/accordion.css
> +  border: 2px solid black;
Исправлено на 1
Но с 2 мне больше нравилось)

2024-03-03 14:24 UTC, Alexandralexv commented on 03-lection1/02-accordion/accordion.css
> +  border-radius: 10px;
Исправлено.

2024-03-03 14:25 UTC, Alexandralexv commented on 03-lection1/02-accordion/accordion.css
> +  padding: 0.5em 0.5em 0.5em;
Исправлено.
8px 8px 8px
А чем em не понравились?

2024-03-03 14:30 UTC, Alexandralexv commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion accordion__item ">
Уже понял :(
Исправлено.

2024-03-03 14:43 UTC, Alexandralexv commented on 03-lection1/02-accordion/accordion.css
> +.accordion {
Исправлено.

2024-03-03 14:46 UTC, Alexandralexv commented on 03-lection1/02-accordion/accordion.css
> +  margin-bottom: 8px;
Добавил стили

2024-03-03 14:46 UTC, Alexandralexv commented on 03-lection1/02-accordion/accordion.css
> +.summary {
Исправлено.

2024-03-04 13:58 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  border: 2px solid black;
у нас работа простая - перевести дизайн в код, и вкусовые предпочтения здесь не важны ;)

2024-03-04 14:01 UTC, GSemikozov requested changes

2024-03-04 14:01 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  padding: 8px 8px 8px;
<img width="276" alt="Screenshot 2024-03-04 at 15 59 17" src="https://github.com/js-tasks-ru/htmlcss-20240216_alexandralexv/assets/6191270/fc049905-b9d5-4147-ae15-901726428c53">
вот такие паддинги должны быть

2024-03-04 14:01 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__content {
margin-top: 16px?

2024-03-04 14:01 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__content {
<img width="435" alt="Screenshot 2024-03-04 at 16 00 04" src="https://github.com/js-tasks-ru/htmlcss-20240216_alexandralexv/assets/6191270/67975aa6-6cfe-4b3e-81b2-166ce1b7fbb2">

2024-03-04 14:01 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  padding: 8px 8px 8px;
а при .accordion__item[open] - снизу будет 32.
<img width="406" alt="Screenshot 2024-03-04 at 16 00 42" src="https://github.com/js-tasks-ru/htmlcss-20240216_alexandralexv/assets/6191270/8e2e54a4-f4d9-40d2-b458-20e3b843fbec">

2024-03-04 14:02 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  padding: 0.5em 0.5em 0.5em;
с em все ок, но лишь до тех пор, пока мы знаем чему равен фонт сайз родителя (здесь - мы не знаем, а значит и не можем быть уверены в том что паддинги здесь всегда стабильны)

2024-03-04 17:07 UTC, Alexandralexv commented on 03-lection1/02-accordion/accordion.css
> +  border: 2px solid black;
Понял. Когда делал задания, думал, что работа немного более творческая :)

2024-03-04 17:07 UTC, Alexandralexv commented on 03-lection1/02-accordion/accordion.css
> +  padding: 0.5em 0.5em 0.5em;
Понял

2024-03-04 17:18 UTC, Alexandralexv commented on 03-lection1/02-accordion/accordion.css
> +  padding: 8px 8px 8px;
Исправил

2024-03-04 17:34 UTC, Alexandralexv commented on 03-lection1/02-accordion/accordion.css
> +.accordion__content {
Это вопрос или утверждение. У меня даже не было margin-top, но теперь есть. Я не очень понял, про что Вы, но теперь между ними 16px, как на графике

2024-03-04 21:54 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  border: 2px solid black;
а вот как выделять блоки и комбинировать их, организовать архитектуру и стили - это уже очень творческая работа :)

2024-03-04 21:55 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__content {
про то что не хватает этого отступа :)

2024-03-04 21:57 UTC, GSemikozov requested changes

2024-03-04 21:57 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  padding: 24px 32px;
я бы все-таки советовал задавать общие паддинги на уровне .accordion__item, и не заморачиваться на уровне .accordion__title + .accordion__content

2024-03-04 21:57 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  margin-top: -8px;
если у тайтла и контента не будет паддингов, то тут марджин будет 16px

2024-03-04 21:57 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  text-align: left;
такое выравнивание - по умолчанию

2024-03-05 07:25 UTC, Alexandralexv commented on 03-lection1/02-accordion/accordion.css
> +  border: 2px solid black;
Согласен

2024-03-05 07:26 UTC, Alexandralexv commented on 03-lection1/02-accordion/accordion.css
> +.accordion__content {
Теперь он есть)

2024-03-05 08:43 UTC, Alexandralexv commented on 03-lection1/02-accordion/accordion.css
> +  text-align: left;
Убрал. 
Не заметил, я их тоже везде убираю.

2024-03-05 08:48 UTC, Alexandralexv commented on 03-lection1/02-accordion/accordion.css
> +  padding: 24px 32px;
Исправил. Согласен, так проще. 
Но в общем и целом, мой вариант тоже рабочий, да?

2024-03-05 08:49 UTC, Alexandralexv commented on 03-lection1/02-accordion/accordion.css
> +  margin-top: -8px;
Исправил. Согласен, так проще.
Но в общем и целом, мой вариант тоже рабочий, да?

2024-03-05 21:27 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  margin-top: -8px;
ага

2024-03-05 21:28 UTC, GSemikozov requested changes

2024-03-05 21:28 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  padding: 24px 32px;
`24 32 32`

2024-03-06 11:52 UTC, Alexandralexv commented on 03-lection1/02-accordion/accordion.css
> +  padding: 24px 32px;
?

2024-03-06 11:54 UTC, Alexandralexv commented on 03-lection1/02-accordion/accordion.css
> +  padding: 24px 32px;
Исправил.

2024-03-06 15:38 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  padding: 24px 32px;
да

2024-03-06 15:38 UTC, GSemikozov approved these changes

2024-03-06 15:38 UTC, merged