Task 4 skeleton
js-tasks-ru/htmlcss-20240216_alexandralexv pull request #7
Opened 2024-03-06 16:42 UTC by Alexandralexv

Я знаю, что тут не правильное решение, но я не понимаю, как его сделать полностью через ```flex```. Направьте меня на путь истинный!

2024-03-06 16:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-12 13:55 UTC, GSemikozov requested changes

2024-03-12 13:55 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.container{
.skeleton

2024-03-12 13:55 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
ширину и высоту убираем

2024-03-12 13:55 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.container-2 {
так-с) все классы надо переписать по БЭМ :)

2024-03-14 13:26 UTC, Alexandralexv commented on 04-lection2/02-skeleton/skeleton.css
> +.container{
Согласен, мне что-то понравилось как вы через контейнер меняли некоторые вещи и я стал их везде пихать :)
Исправлено

2024-03-14 13:28 UTC, Alexandralexv commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
Исправлено.

2024-03-14 13:38 UTC, Alexandralexv commented on 04-lection2/02-skeleton/skeleton.css
> +.container-2 {
Его уже нет. Я видимо опять забыл запушить последние коммиты...

2024-03-14 13:58 UTC, Alexandralexv commented on 04-lection2/02-skeleton/skeleton.css
> +.container-2 {
Переписал классы по БЭМ, я уверен, что Вам опять не понравится...Просто голову себе ломаю, чтобы их нормально писать

2024-03-14 14:09 UTC, Alexandralexv commented
В попытках исправить БЭМ, я полкода переписал...

2024-03-14 14:37 UTC, GSemikozov requested changes

2024-03-14 14:37 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    height: 70px;
64x64

2024-03-14 14:37 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin: -8px 0 0 0;
нет, на уровне блока паддинг сверху 24 и тогда здесь не нжен отрицательный марджин)

2024-03-14 14:37 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  .skeleton__rectangle_1 {
лучше семантически имена классов - .skeleton__rectangle_small и тд

2024-03-14 14:37 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
ширину - в процентах

2024-03-14 14:37 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    background-color: #DDE2E5;
лишнее

2024-03-14 14:37 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    height: 20px;
лишнее

2024-03-14 14:51 UTC, Alexandralexv commented on 04-lection2/02-skeleton/skeleton.css
> +    background-color: #DDE2E5;
Согласен

2024-03-14 14:51 UTC, Alexandralexv commented on 04-lection2/02-skeleton/skeleton.css
> +    height: 20px;
Согласен

2024-03-14 14:53 UTC, Alexandralexv commented on 04-lection2/02-skeleton/skeleton.css
> +    height: 70px;
Да, в фигме 64х64, без понятия, почему я 70 написал.
Исправлено.

2024-03-14 14:53 UTC, Alexandralexv commented on 04-lection2/02-skeleton/skeleton.css
> +    margin: -8px 0 0 0;
![image](https://github.com/js-tasks-ru/htmlcss-20240216_alexandralexv/assets/122827524/731ef62b-24e2-48b0-936d-5a84737953c0)

2024-03-14 14:54 UTC, Alexandralexv commented on 04-lection2/02-skeleton/skeleton.css
> +    margin: -8px 0 0 0;
В фигме видно, что именно круг вылезает за пределы.

2024-03-14 14:54 UTC, Alexandralexv commented on 04-lection2/02-skeleton/skeleton.css
> +    margin: -8px 0 0 0;
А если делать по "Вашему", то надо будет у верхнего прямоугольника margin дополнительный делать

2024-03-14 14:59 UTC, Alexandralexv commented on 04-lection2/02-skeleton/skeleton.css
> +  .skeleton__rectangle_1 {
.skeleton__rectangle_one,two,three, подойдёт?)))

2024-03-14 15:01 UTC, Alexandralexv commented on 04-lection2/02-skeleton/skeleton.css
> +  .skeleton__rectangle_1 {
Исправил

2024-03-14 15:02 UTC, Alexandralexv commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
От куда их брать?

2024-03-14 15:15 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin: -8px 0 0 0;
ну а если взять слой вместе с кругом - то видно что все ок)

2024-03-14 15:16 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
приблизительно

2024-03-14 15:16 UTC, GSemikozov requested changes

2024-03-14 15:16 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 515px;
в процентах

2024-03-14 15:23 UTC, Alexandralexv commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 515px;
Оно вообще не нужно, я забыл убрать, после того как тестил разные варианты.

2024-03-14 15:24 UTC, Alexandralexv commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
Я посчитал на калькуляторе)

2024-03-14 15:24 UTC, Alexandralexv commented on 04-lection2/02-skeleton/skeleton.css
> +    margin: -8px 0 0 0;
Хорошо

2024-03-14 15:30 UTC, GSemikozov approved these changes

2024-03-14 15:30 UTC, merged